# Generated by Django 5.0.3 on 2024-10-30 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0003_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="create_time",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
