# Generated by Django 5.0.3 on 2024-10-30 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0004_tag_create_time_alter_tag_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"ordering": ["-pub_time", "name"]},
        ),
        migrations.AlterModelTable(
            name="book",
            table="book_table",
        ),
    ]
